name: CI
on:
  schedule:
  - cron: "0 * * * 2"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        token: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
    - name: Monitor altdns
      run: |
        pip install --no-deps py-altdns
        pip show py-altdns > altdns_version
    - name: Commit altdns_version
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add altdns_version
        git commit -m "New altdns version" -a
        git push "https://phasip:${{ secrets.GITHUB_PERSONAL_TOKEN }}@github.com/phasip/altdns-docker.git" HEAD:master --follow-tags
